training:
  batch_size: 128
  n_epochs: 3000
  n_iters: 100000
  algo: "ssm"

data:
  dataset: "MNIST"
  image_size: 28
  channels: 1

model:
  n_particles: 1
  z_dim: 32
  eps_dim: 32
  nef: 16
  ndf: 16

optim:
  weight_decay: 0.000
  optimizer: "RMSProp"
  lr: 0.001
